platform: linux

image_resource:
  type: docker-image
  source:
    repository: ddubson/rb-go-java-node-erl-py
    tag: v2

inputs:
- name: LicenseFinder

run:
  path: ./LicenseFinder-CI/ci/test.sh

params:
  RUBY_VERSION:
